<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="<?php echo $this->getLang() ?>" lang="<?php echo $this->getLang() ?>">
<head>
<?php echo $this->getChildHtml('head') ?>
<script type="text/javascript" src="http://fast.fonts.net/jsapi/55222375-0ea5-4ca5-bc1b-11874820c8ae.js"></script>

</head>

<body<?php echo $this->getBodyClass()?' class="cms-vintage '.$this->getBodyClass().'"':'' ?>>
<?php echo $this->getChildHtml('after_body_start') ?>
<div class="wrapper">

    <?php echo $this->getChildHtml('global_notices') ?>
    <?php echo $this->getChildHtml('header') ?>
    <?php echo $this->getChildHtml('global_messages') ?>

    <div class="navi_sub">
        <a href="/release#editions">EDITIONS &amp; STORIES</a>
        <a href="/manufacturing">OUR MANUFACTURING</a>
        <a href="/open-lab-traceability">TRACE YOUR PRODUCT</a>
        <a href="#ol-faq">FAQ</a>
    </div>
    
    <div class="page">
        <div class="main col1-layout">
            <div class="col-main noshadow">
                
                 <!-- Main Content Box -->
                <div class="generic_box_full imgcenter">
                    

                    <div class="phantomvideo_contain">
                        <img src="/skin/frontend/enterprise/default/images/ol/v/1.jpg" />
                        <div class="phantom">
                            <a href="#" onClick="playVideo();return false;"><img src="/skin/frontend/enterprise/default/images/ol/v/1-vid.jpg" /></a>
                        </div>
                        <div class="one-desc desc">
                            <h1>We are not just a brand.</h1>
                            <p>Our energy and passion goes into <span class="green">inventing</span> the finest 100% natural skincare in the world, and <span class="green">batching it ourselves.</span> We believe that when it comes to your skincare, the fewer mysteries, the better. Now, discover <span class="green">how</span> - and <span class="green">why</span> that matters.</p>
                        </div>
                    </div>
                    
                    <img src="/skin/frontend/enterprise/default/images/ol/v/2.jpg" class="vspacer" />
                        <div class="cta_hovers">
                            <a href="/release#bios"><img src="/skin/frontend/enterprise/default/images/ol/v/2.1.jpg" onmouseover="this.src='/skin/frontend/enterprise/default/images/ol/v/2.1.h.jpg'" onmouseout="this.src='/skin/frontend/enterprise/default/images/ol/v/2.1.jpg'" /></a>
                            
                            <a href="#trackit"><img src="/skin/frontend/enterprise/default/images/ol/v/2.2.jpg" onmouseover="this.src='/skin/frontend/enterprise/default/images/ol/v/2.2.h.jpg'" onmouseout="this.src='/skin/frontend/enterprise/default/images/ol/v/2.2.jpg'" /></a>
                            
                            <a href="/release#editions"><img src="/skin/frontend/enterprise/default/images/ol/v/2.3.jpg" onmouseover="this.src='/skin/frontend/enterprise/default/images/ol/v/2.3.h.jpg'" onmouseout="this.src='/skin/frontend/enterprise/default/images/ol/v/2.3.jpg'" /></a>
                        </div>
                    <div id="trackit" class="tracerbox">
                        <img src="/skin/frontend/enterprise/default/images/ol/v/3.jpg" class="bspacer" />
                       
                        <div class="phantombox">
                            <form action="/release?utm_source=web&utm_medium=track&utm_campaign=release" method="post" class="trackerinfo">
                                <input type="text" name="one" maxlength="1" />
                                <input type="text" name="two" maxlength="1" />
                                <input type="text" name="three" maxlength="1" />
                                <input type="submit" value="Go" />
                            </form>
                        </div>

                        <div class="three-desc desc">
                            <h1>Discover when your product<br />was made!</h1>
                            <p><span class="bold">Trace your bottle to its origin in our lab by</span> entering the first three digits of the number on the bottom of your Tata Harper Skincare bottle.</p>
                        </div>

                    </div>
                    <div class="phantom-contain">
                        <a href="/release#bios"><img src="/skin/frontend/enterprise/default/images/ol/v/4.jpg" class="bspacer" /></a>
                        <div class="four-desc desc">
                            <h1>We believe in an<br />unspoken promise</h1>
                            <p>Between us and our customers that Tata Harper products are made by Tata Harper employees, not by an outsourced company. We want the logo on the bottle to really mean something.</p>
                            <a href="/release#bios" class="cta">Meet the Team</a>
                        </div>
                    </div>
                    <div class="phantom-contain">
                        <a href="/manufacturing"><img src="/skin/frontend/enterprise/default/images/ol/v/5.jpg" class="bspacer" /></a>
                        <div class="five-desc desc">
                            <h1>To us, beauty is about<br />authenticity.</h1>
                            <p>Hand-crafting proprietary, natural and high-performance skincare that has the power to transform people's skin (and therefore their lives!) for the better is what we love to do, and it's why we're in business.</p>
                            <a href="/manufacturing" class="cta">Learn more about our manufacturing</a>

                        </div>
                    </div>
                    <div class="phantom-contain">
                        <a href="/release#editions"><img src="/skin/frontend/enterprise/default/images/ol/v/6.jpg" /></a>
                        <div class="six-desc desc">
                            <h1>What's changing?</h1>
                            <p>The efficacy of our products will never change, but your experience might, always for good reason and in our opinion, for the better. These are the same formulas you know and love - with the added benefit of truth and transparency, so you can see behind the curtain into our world as we consistently create the world's finest all-natural skincare.</p>
                            <a href="/release#bios" class="cta">Explore the editions library</a>

                        </div>

                    </div>
                </div>

            </div>
        </div>
    </div>

<div class="page full gray">
    <div class="main col1-layout">
        <div class="noshadow">

    <div class="generic_box_full_wide skincarestory">
            
            <img src="/skin/frontend/enterprise/default/images/ol/v/storyheader.jpg" style="margin-top:1em;" />
        
        <div id="slider" class="nivoSlidervin">
            <img src="/skin/frontend/enterprise/default/images/ol/v/pg1.jpg" title="Tata Harper Skincare was founded by Tata Harper with the idea that women shouldn’t have to sacrifice their health to look and feel beautiful, and that skincare should be able to deliver real, visible results without a single drop of synthetic chemicals." />
            <img src="/skin/frontend/enterprise/default/images/ol/v/pg2.jpg" title="Since the beginning, we’ve felt a commitment to authenticity, trust and transparency. Our company, including our labs, has been based in Vermont since the birth of the company, and our own passionate team hand crafts each batch of Tata Harper skincare product from start to finish." />
            <img src="/skin/frontend/enterprise/default/images/ol/v/pg3.jpg" title="Our formulas were developed over the course of five years by a team of eight leading European chemists, who collectively set out to challenge the idea that “natural” couldn’t mean “effective”. Using the latest clinically proven skincare science from around the world, the Core line was released in 2010." />
            <img src="/skin/frontend/enterprise/default/images/ol/v/pg4.jpg" title="Our fascinating ingredients lend a rich background to each unusually concentrated formula: our ingredients are real, natural and exquisite and are brought from amazing places in the world – like the Amazon, Tasmania, Morocco, the Czech Republic, Spain and Israel. We grow what we can here on our own Organic Vermont farm." />
        </div>

     </div>

        </div>
    </div>
</div>

<div class="page full">
    <div class="main col1-layout">
        <div class="noshadow">

     <div class="generic_box_full howitworks imgcenter">

        <img src="/skin/frontend/enterprise/default/images/ol/v/howworks.jpg" style="margin-bottom:1em" />

        <div id="slidersecond" class="nivoSlidervin2">
             <img src="/skin/frontend/enterprise/default/images/ol/v/create_37.jpg" />
             <img src="/skin/frontend/enterprise/default/images/ol/v/trace_37.jpg" />
             <img src="/skin/frontend/enterprise/default/images/ol/v/discover_37.jpg" />
             <img src="/skin/frontend/enterprise/default/images/ol/v/editions_37.jpg" />
         </div>
     </div>

        </div>
    </div>
</div>

<div class="page full">
    <div class="greenbg">
        <img src="/skin/frontend/enterprise/default/images/ol/v/havequestion.jpg" class="centerimage" />
        <h3>See if we've answered it already in this list of common questions, along with our answers for each one. If not, send us an email with your inquiry at <a href="mailto:info@tataharper.com">info@tataharper.com</a>, or give us a ring at 1-877-321-8282 to chat. Thanks!</h3>
        <a id="ol-faq" class="faq" href="#"><img src="/skin/frontend/enterprise/default/images/ol/v/ctafaq.jpg" /></a>
    </div>
</div>

    <?php echo $this->getChildHtml('footer_before') ?>
    <?php echo $this->getChildHtml('footer') ?>
    <?php echo $this->getChildHtml('before_body_end') ?>
</div>
<?php echo $this->getAbsoluteFooter() ?>

    <!-- Call Nivo, move this later after testing -->

    <script type="text/javascript">

    function playVideo() {
        var one = "<div class='popup vimeo'>";
        var two = '<iframe src="//player.vimeo.com/video/102090527" width="920" height="515" frameborder="0" webkitallowfullscreen mozallowfullscreen allowfullscreen></iframe>';
        var three = "</div>";
        var coolhtml = jQuery(one + two + three);
        jQuery.colorbox({html:coolhtml, width:"960px", height:"560px"});
    }

        jQuery(window).load(function() {
         jQuery('#slider').nivoSlider({
            effect: 'fade',
            prevText: 'p',
            nextText: 'n',
            manualAdvance: true,
            controlNav: false
         });
        });
        jQuery(window).load(function() {
         jQuery('#slidersecond').nivoSlider({
            effect: 'fade',
            prevText: 'p',
            nextText: 'n',
            manualAdvance: true,
            controlNav: false
         });
        });

        

        </script>
</body>
</html>
