<div id="navigation">
	<div id="megaMenu" class="megaMenuContainer megaFullWidth megaMenuHorizontal">
		<ul id="megaUber" class="megaMenu">

		    <li class="menu-item">
		    	<a href="/shop-all-skincare">Skincare</a>

						<div class="dropdown_3column submenu skincare-menu">
			              
			      		<div class="col_1" style="width:15.2%;margin-left:23px;">
			            
						<ul>
							<li><a href="http://www.tataharperskincare.com/online-exclusives" class="bolditem">What's New</a></li>
							<li><a href="http://www.tataharperskincare.com/shop-all-skincare" class="bolditem">SHOP ALL SKINCARE</a></li>
							<li><a href="http://www.tataharperskincare.com/beauty-and-gift-sets" class="bolditem">KITS &amp; GIFTS</a></li>
							<li><a href="http://www.tataharperskincare.com/cat-supernatural-collection" class="bolditem">SUPERNATURAL COLLECTION</a></li>
						</ul>

			            </div>

			            <div class="col_1" style="width:25%;margin-left:35px;">
			         
			                <ul>
								<li><a href="#" class="bolditem">SHOP SKINCARE BY CATEGORY</a>
								<li><a href="/antiage">Antiaging Serums</a></li>
								<li><a href="/cleanse">Cleansers</a></li>
								<li><a href="/moisturize">Moisturizers &amp; Toners</a></li>
								<li><a href="/mask">Masks</a></li>
								<li><a href="/restorative-eye-creme">Eye Cream</a></li>
								<li><a href="/exfoliators">Exfoliators</a></li>
								<li><a href="body">Body</a></li>
							</li>

			            </div>

			            <div class="col_1" style="width:14.5%;margin-left:10px;">  

							<ul>
							<li><a href="http://www.tataharperskincare.com/skincare/shop-by-category" class="bolditem">Shop by concern</a></li>

								<li><a href="http://www.tataharperskincare.com/antiage">Antiaging</a></li>
								<li><a href="http://www.tataharperskincare.com/sensitivity">Sensitivity</a></li>
								<li><a href="http://www.tataharperskincare.com/discoloration">Discoloration</a></li>
								<li><a href="http://www.tataharperskincare.com/redness">Redness</a></li>
								<li><a href="http://www.tataharperskincare.com/hydration">Hydration</a></li>
								<li><a href="http://www.tataharperskincare.com/radiance">Radiance</a></li>
								<li><a href="http://www.tataharperskincare.com/pores">Pores</a></li>
								<li><a href="http://www.tataharperskincare.com/breakouts">Breakouts</a></li>
							</ul>

			            </div>

			            <div class="menuimg_right">
			            	<a href="/beautifying-face-oil"><img src="//www.tataharperskincare.com/blasts/desktophome/nav_skincare.jpg"></a>
			            </div>
			              
			        </div>

		    </li>

		    <li class="menu-item">
		    	<a href="/best-sellers">Best Sellers</a>
		    </li>

		    <li class="menu-item">
		    	<a href="/shop-by-aromatherapy">Aromatherapy</a>

		    	<div class="dropdown_2column submenu aroma-menu">
			      
			            <div class="col_1" style="width:40%;margin-top:15px;margin-left:20px;">
			                <ul>
						    <li><a href="/aromatherapy/#tabs-1" onclick="window.location.href = '#tabs-1';location.reload();" class="bolditem">Why Aromatherapy?</a></li> 
						    <li><a href="/aromatherapy/#tabs-2" onclick="window.location.href = '#tabs-2';location.reload();" class="bolditem">How it Works</a></li> 
						    <li><a href="/shop-by-aromatherapy" class="bolditem">Shop Aromatherapy</a></li> 
						        <li><a href="/aromatic-bedtime-treatment">Aromatic Bedtime Treatment</a></li> 
						        <li><a href="/aromatic-stress-treatment">Aromatic Stress Treatment</a></li> 
						        <li><a href="/aromatic-irritability-treatment">Aromatic Irritability Treatment</a></li>
						        <li><a href="/love-potion-5-ml">Love Potion</a></li>
			                </ul> 
			            </div>

			            <div class="menuimg_right">
			            	<a href="/shop-by-aromatherapy"><img src="//www.tataharperskincare.com/blasts/desktophome/nav_lovepoti.jpg"></a>
			            </div>
			              
			    </div>
			    
		    </li>
		    <li class="menu-item">
		    	<a href="/shop-by-lip-care" onclick="window.location.href = '#tabs-3';location.reload();">Cosmetics</a>
		    </li>
		    <li class="menu-item">
		    	<a href="/tatas-mission">Tata's World</a>

				<div class="dropdown_2column item-5 submenu world-menu" style="padding:0px;width:477px;">
			      
			            <div class="col_1" style="width:20%;margin-left:20px;">
			                <ul>
							<li><a href="/tatas-mission" class="bolditem">Tata's Mission</a></li> 
							<li><a href="http://www.tataharperskincare.com/tatas-world" class="bolditem">TATA'S PHOTOSTREAM</a></li> 
							<li><a href="http://blog.tataharperskincare.com/" class="bolditem">The Blog</a></li> 
							<li><a href="/videos" class="bolditem">Watch Tata</a></li>
							</ul>
			            </div>

			            <div class="col_1" style="width:13.5%;margin-left:20px;">
								<ul>
								<li><a href="#" class="bolditem">Follow Tata</a></li>
								<li><a href="https://instagram.com/tataharper" target="_blank">Instagram</a></li>
								<li><a href="http://pinterest.com/tataharper/" target="_blank">Pinterest</a></li>
								<li><a href="https://www.facebook.com/TataHarperSkinCare" target="_blank">Facebook</a></li>
								<li><a href="https://twitter.com/TataHarper" target="_blank">Twitter</a></li>
								</ul>
			            </div>

						<div class="menuimg_right">
							<a href="/tatas-mission"><img src="//www.tataharperskincare.com/blasts/desktophome/meet_tata.jpg"></a>
						</div>

			    </div>

		    </li>

		    <li class="menu-item">
		    	<a href="/why-we-are-different">About Us</a>

		    	<div class="dropdown_2column item-7 submenu about-menu" style="padding:0px;width:680px;margin-left:-303px;">
			      
			            <div class="col_1" style="width:25%;margin-left:20px;">
			            <ul>
			            	<li><a href="/press-awards" class="bolditem">Press &amp; Awards</a></li>
			                <li><a href="/why-we-are-different" class="bolditem">Why We are Different</a></li>
			                <li><a href="/about-us/our-certifications">Our Certifications</a></li>
							<li><a href="/about-us/our-farm">Our Farm</a></li> 
							<!-- <li><a href="/our-lab/ingredients">Our Ingredients</a></li> -->


							<li><a href="http://www.tataharperskincare.com/manufacturing" class="bolditem">How it's made: Product manufacturing</a></li>

							<!-- <li><a href="/our-lab" class="bolditem">Go Inside Our Lab</a></li> -->
							<li><a href="/shop-by-antiaging/#tabs-2" onclick="window.location.href = '#tabs-2';location.reload();">Our Technology</a></li>
							<!-- <li><a href="/our-lab/#tabs-3" onclick="window.location.href = '#tabs-3';location.reload();">Results from Natural Actives</a></li> -->
							<!-- <li><a href="/our-lab/#tabs-4" onclick="window.location.href = '#tabs-4';location.reload();">Meet our Lab Team</a></li> -->
							<li><a href="/shop-by-antiaging/#tabs-1" onclick="window.location.href = '#tabs-1';location.reload();">Discover Antiaging Technology</a></li>

							<li><a href="/about-us/pricing-philosophy" class="bolditem">Pricing Philosophy</a></li>
							
							</ul>
						</div>

			            <div class="menuimg_right">
			            	<a href="/about-us/our-farm"><img src="//www.tataharperskincare.com/blasts/desktophome/nav_our_farm.jpg"></a>
			            </div>

			    </div>

		    </li>
		     <!-- <li class="menu-item">
		    	<a href="/vintage">Open Lab</a>

		    	    	<div class="dropdown_2column submenu lab-menu">
		    		      
		    		            <div class="col_1" style="width:30%;margin-top:15px;margin-left:20px;">
		    		                <ul>
		    					    <li><a href="/vintage" class="bolditem">OPEN LAB &amp; traceability program</a></li>  
		    					    <li><a href="/release#editions" class="bolditem">EDITIONS &amp; STORIES</a></li>  
		    					    <li><a href="/manufacturing" class="bolditem">OUR MANUFACTURING</a></li>
		    					    <li><a href="#" class="faq bolditem">PROGRAM FAQ</a></li>
		    		                </ul> 
		    		            </div>

		    		            <div class="menuimg_right last">
		    		            	<a href="/vintage"><img src="//www.tataharperskincare.com/blasts/desktophome/trace_product.jpg"></a>
		    		            </div>
		    		              
		    		    </div>

		    </li> -->
		     <li class="menu-item">
		    	<a href="http://blog.tataharperskincare.com">Blog</a>
		    </li>
		    
			<li class="menu-item">
				<a href="/videos">Videos</a>
			</li>

		    <!--  <li class="menu-item">
		    	<a href="/beauty-and-gift-sets">Holiday Gifts</a>

		    	    	<div class="dropdown_2column submenu kits-menu">
		    		      
		    		            <div class="col_1" style="width:25%;margin-top:15px;margin-left:20px;">
		    		                <ul>
		    					    <li><a href="/beauty-and-gift-sets" class="bolditem">Value Sets</a></li> 
		    					    <li><a href="/tatas-natural-beauty-gift-guide" class="bolditem">Gift Guide</a></li> 
		    					    <li><a href="/gift-cards" class="bolditem">Gift Cards</a></li> 
		    					        <li><a href="#">Printed Gift Card</a></li> 
		    					        <li><a href="/gift-card">E-Gift Card</a></li> 
		    		                </ul> 
		    		            </div>

		    		            <div class="menuimg_right">
		    		            	<a href="/tata-s-daily-essentials-natural-antiaging-skincare-discovery-kit"><img src="//www.tataharperskincare.com/blasts/desktophome/nav_kitsandgifts.jpg"></a>
		    		            </div>
		    		              
		    		    </div>

		    </li> -->

		</ul>
	</div>
</div>