<?php
/**
 * Register form
 */
?>
<?php echo $this->getMessagesBlock()->getGroupedHtml() ?>

<div class="my-account generic_box_full">
	<!-- <div class="page-title">
		<h2><?php //echo $this->__('Signup Affiliate System'); ?></h2>
	</div> -->
	
	<!-- <form id="signup_affiliate_account_form" class="custom-affiliate-signup" method="post" onsubmit="customAffiliateSignup()" action="<?php //echo $this->getUrl('affiliateplus/account/createPost') ?>"> -->
	<form id="signup_affiliate_account_form" class="custom-affiliate-signup" method="post" action="<?php echo $this->getUrl('affiliateplus/account/createPost') ?>">
		<?php //if (!$this->customerLoggedIn()): ?>
			<h2 class="legend green"><?php echo $this->__('Tata Harper Affiliate Program') ?></h2>
			<p class="subtitle">Submit your application to apply to join our Affiliate Program.</p>
			<p>How to submit:</p>
			<ul class="aff_overview">
				<li><span>Step 1:</span> Complete the basic entry form below.</li>
				<li><span>Step 2:</span> Share information on your site content.</li>
				<li><span>Step 3:</span> Our Affiliate team will review your site. <em>If your site is approved for the program, our Affiliate team will contact you.</em></li>
			</ul>
			<div class="fieldset clearfix">
			<ul class="form-list">
				<h2 class="listitem"><span>1</span> Approval Process</h2>
				<?php if (!$this->customerLoggedIn()): ?>
				<li class="fields">
					<div class="customer-name">
						<div class="field name-firstname">
							<label class="required" for="firstname"><em>*</em><?php echo $this->__('First Name') ?></label>
							<div class="input-box">
								<input type="text" class="input-text required-entry" title="First Name" name="firstname" id="firstname" value="<?php echo $this->getFormData('firstname')?>">
							</div>
						</div>
						<div class="field name-lastname">
							<label class="required" for="lastname"><em>*</em><?php echo $this->__('Last Name') ?></label>
							<div class="input-box">
								<input type="text" class="input-text required-entry" title="Last Name"  name="lastname" id="lastname" value="<?php echo $this->getFormData('lastname')?>">
							</div>
						</div>
					</div>
				</li>
				<li>
					<label for="email_address" class="required"><em>*</em><?php echo $this->__('Email Address') ?></label>
					<div class="input-box">
						<input type="text" name="email" id="email_address" onchange="checkEmailRegister('<?php echo $this->getCheckCustomerEmailUrl(); ?>', 'signup_account_account_form');" title="<?php echo $this->__('Email Address') ?>" class="input-text validate-email required-entry" value="<?php echo $this->getFormData('email')?>" />
						<span id="affiliate-please-wait-email" style="display:none;" class="opc-please-wait">
							<img src="<?php echo $this->getSkinUrl('images/opc-ajax-loader.gif') ?>" class="v-middle" alt="" /> &nbsp; <?php echo $this->__('Checking email address') ?>...
						</span>
						<div id="affiliate_message_hidden_email" class="affiliate_message"></div>
						<div class="affiliate_message" id="affiliate_message_email" style="display:none">
							<?php echo $this->__('This account Name is existed. Please enter other account Name.'); ?>
						</div>
				   </div>
				</li>
			<?php if (0 && Mage::helper('core')->isModuleOutputEnabled('Mage_Newsletter')): ?>
				<li class="control">
					<div class="input-box">
						<input type="checkbox" name="is_subscribed" title="<?php echo $this->__('Sign Up for Newsletter') ?>" value="1" id="is_subscribed"<?php if($this->getFormData('is_subscribed')): ?> checked="checked"<?php endif; ?> class="checkbox" />
					</div>
					<label for="is_subscribed"><?php echo $this->__('Sign Up for Newsletter') ?></label>
				</li>
			<?php endif ?>
			<?php $_dob = $this->getLayout()->createBlock('customer/widget_dob') ?>
			<?php if ($_dob->isEnabled()): ?>
				<li><?php echo $_dob->setDate($this->getFormData('dob'))->toHtml() ?></li>
			<?php endif ?>
			<?php $_taxvat = $this->getLayout()->createBlock('customer/widget_taxvat') ?>
			<?php if ($_taxvat->isEnabled()): ?>
				<li><?php echo $_taxvat->setTaxvat($this->getFormData('taxvat'))->toHtml() ?></li>
			<?php endif ?>
			<?php $_gender = $this->getLayout()->createBlock('customer/widget_gender') ?>
			<?php if ($_gender->isEnabled()): ?>
				<li><?php echo $_gender->setGender($this->getFormData('gender'))->toHtml() ?></li>
			<?php endif ?>
				<li class="fields">
					<div class="field">
						<label for="password" class="required"><em>*</em><?php echo $this->__('Password') ?></label>
						<div class="input-box">
							<input type="password" name="password" id="password" title="<?php echo $this->__('Password') ?>" class="input-text required-entry validate-password" />
						</div>
					</div>
					<div class="field">
						<label for="confirmation" class="required"><em>*</em><?php echo $this->__('Confirm Password') ?></label>
						<div class="input-box">
							<input type="password" name="confirmation" title="<?php echo $this->__('Confirm Password') ?>" id="confirmation" class="input-text required-entry validate-cpassword" />
						</div>
					</div>
				</li>
				<?php endif ?>
			<!--/ul>
		</div>
		<?php //endif ?>
		
		<?php if ($this->requiredAddress()): ?>
		<div class="fieldset">
			<h2 class="legend"><?php echo $this->__('Address Information') ?></h2>
			<ul class="form-list"-->
			<?php if ($this->customerHasAddresses()): ?>
				<li class="wide">
					<label for="customer-address-select"><?php echo $this->__('Select an address from your address book or enter a new address.') ?></label>
					<div class="input-box">
						<?php echo $this->getAddressesHtmlSelect('account') ?>
					</div>
				</li>
			<?php endif; ?>
			<li id="account-new-address-form" <?php if ($this->customerHasAddresses()): ?> style="display:none;"<?php endif; ?>>
				<fieldset>
					<input type="hidden" name="account[address_id]" value="<?php echo $this->getAddress()->getId() ?>" id="account:address_id" />
					<ul>
						<li class="wide">
							<label for="account:street1" class="required"><em>*</em><?php echo $this->__('Address') ?></label>
							<div class="input-box">
								<input type="text" title="<?php echo $this->__('Street Address') ?>" name="account[street][]" id="account:street1" value="<?php echo $this->htmlEscape($this->getAddress()->getStreet(1)) ?>" class="input-text required-entry" />
							</div>
						</li>
				<?php for ($_i=2, $_n=$this->helper('customer/address')->getStreetLines(); $_i<=$_n; $_i++): ?>
						<li class="wide">
							<label for="account:street<?php echo $_i?>"></label>
							<div class="input-box">
								<input type="text" title="<?php echo $this->__('Street Address %s', $_i) ?>" name="account[street][]" id="account:street<?php echo $_i?>" value="<?php echo $this->htmlEscape($this->getAddress()->getStreet($_i)) ?>" class="input-text" />
							</div>
						</li>
				<?php endfor ?>
						<li class="fields">
							<div class="field">
								<label for="account:city" class="required"><em>*</em><?php echo $this->__('City') ?></label>
								<div class="input-box">
									<input type="text" title="<?php echo $this->__('City') ?>" name="account[city]" value="<?php echo $this->htmlEscape($this->getAddress()->getCity()) ?>" class="input-text required-entry" id="customer:city" />
								</div>
							</div>
							<div class="field">
								<label for="account:region_id" class="required"><em>*</em><?php echo $this->__('State/Province') ?></label>
								<div class="input-box">
									<select id="account:region_id" name="account[region_id]" title="<?php echo $this->__('State/Province') ?>" class="validate-select" style="display:none;">
										<option value=""><?php echo $this->__('Please select region, state or province') ?></option>
									</select>
									<script type="text/javascript">
									//<![CDATA[
										$('account:region_id').setAttribute('defaultValue',  "<?php echo $this->getAddress()->getRegionId() ?>");
									//]]>
									</script>
									<input type="text" id="account:region" name="account[region]" value="<?php echo $this->htmlEscape($this->getAddress()->getRegion()) ?>"  title="<?php echo $this->__('State/Province') ?>" class="input-text" style="display:none;" />
								</div>
							</div>
						</li>
						<li class="fields">
							<div class="field">
								<label for="account:postcode" class="required"><em>*</em><?php echo $this->__('Zip/Postal Code') ?></label>
								<div class="input-box">
									<input type="text" title="<?php echo $this->__('Zip/Postal Code') ?>" name="account[postcode]" id="account:postcode" value="<?php echo $this->htmlEscape($this->getAddress()->getPostcode()) ?>" class="input-text validate-zip-international required-entry" />
								</div>
							</div>
							<div class="field">
								<label for="account:country_id" class="required"><em>*</em><?php echo $this->__('Country') ?></label>
								<div class="input-box">
									<?php echo $this->getCountryHtmlSelect('account') ?>
								</div>
							</div>
						</li>
						<li lang="fields">
							<div class="field">
								<label for="account:telephone" class="required"><em>*</em><?php echo $this->__('Telephone') ?></label>
								<div class="input-box">
									<input type="text" name="account[telephone]" value="<?php echo $this->htmlEscape($this->getAddress()->getTelephone()) ?>" title="<?php echo $this->__('Telephone') ?>" class="input-text required-entry" id="account:telephone" />
								</div>
							</div>
							<div class="field">
								<label for="account:fax"><?php echo $this->__('Fax') ?></label>
								<div class="input-box">
									<input type="text" name="account[fax]" value="<?php echo $this->htmlEscape($this->getAddress()->getFax()) ?>" title="<?php echo $this->__('Fax') ?>" class="input-text" id="account:fax" />
								</div>
							</div>
						</li>
					</ul>
				</fieldset>
			 </li>
			<!--/ul>
		</div>
		<?php endif ?>
		
		<div class="fieldset">
			<h2 class="legend"><?php echo $this->__('Affiliate Account Information'); ?></h2>
			<ul class="form-list"-->
				<?php if ($this->getFormData('account_name')): ?>
				<li class="fields">
					<div class="field account-name">
						<label for="account_name"><?php echo $this->__('Name'); ?></label>
						<div class="input-box">
							<strong>
								<span><?php echo $this->getFormData('account_name') ?></span>
							</strong>
							<input id="account_name" type="hidden" title="<?php echo $this->__('Name'); ?>" name="account_name"  value="<?php echo $this->getFormData('account_name')?>"/>
						</div>
						<div id="affiliate_message_hidden" class="affiliate_message"></div>
					</div>
				</li>
				<?php endif ?>
				<li class="fields">
					<div class="field paypal-email">
					<!-- Added by AX on September 5 for Affiliate Signup page -->

					<?php if ($this->customerLoggedIn()): ?>
					<?php
						$customer = Mage::getSingleton('customer/session')->getCustomer();
						$email = $customer->getEmail();
					?>
						<input id="logged_in_customer_email" type="hidden" name="logged_in_customer_email" value="<?php echo $email ?>" />
					<?php endif; ?>
					<!-- End additions by AX -->

					<?php if ($this->requiredPaypal()): ?>
						<label class="required" for="paypal_email"><em>*</em><?php echo $this->__('Paypal Email'); ?></label>
						<div class="input-box">
							<input id="paypal_email" class="input-text required-entry validate-email" type="text" title="<?php echo $this->__('Paypal Email'); ?>" name="paypal_email" value="<?php echo $this->getFormData('paypal_email')?>"/>
						</div>
					<?php else: ?>
						<label for="paypal_email"><?php echo $this->__('Paypal Email'); ?></label>
						<div class="input-box">
							<input id="paypal_email" class="input-text validate-email" type="text" title="<?php echo $this->__('Paypal Email'); ?>" name="paypal_email" value="<?php echo $this->getFormData('paypal_email')?>"/>
						</div>
					<?php endif ?>
					</div>
					<div class="field">
						<label for="notification"><?php echo $this->__('Receive Notification Email') ?></label>
						<div class="input-box">
							<select name="notification" id="notification" class="input-select">
								<option value="0"><?php echo $this->__('No') ?></option>
								<option value="1" selected="selected"><?php echo $this->__('Yes') ?></option>
							</select>
						</div>
					</div>
				</li>
				<!-- <li class="fields">
					<div class="field">
						<label class="required" for="account_captcha"><em>*</em><?php echo $this->__('Verification'); ?></label>
						<div class="input-box">
							<img src="<?php echo $this->getUrl('affiliateplus/account/imagecaptcha');?>" id="account_captcha_image" />
							<span id="affiliate-please-wait-captcha" style="display:none;" class="opc-please-wait">
								<img src="<?php echo $this->getSkinUrl('images/opc-ajax-loader.gif') ?>" class="v-middle" alt="" /> &nbsp; <?php echo $this->__('Getting new captcha') ?>...
							</span>
							<a href="javascript:void(0);" onclick="refreshCaptchaImage();return false;" id="affiliate-captcha-link"><?php echo $this->__("Refresh"); ?></a>
						</div>
					</div>
				</li> -->
				<li class="fields">
					<div class="field">
						<label for="account_captcha"></label>
						<div class="input-box">
							<input id="account_captcha" class="input-text required-entry" type="text" title="<?php echo $this->__('Captcha code') ?>" name="account_captcha" />
						</div>
					</div>
				</li>
				<!-- EXTRA 1 -->
				<li class="fields">
					<div class="field">
						<label for="phone_number_extra"><em>*</em><?php echo $this->__('Phone Number'); ?></label>
						<div class="input-box">
							<input id="phone_number_extra" class="phone_number_extra required-entry" type="text" title="<?php echo $this->__('Phone Number') ?>" name="phone_number_extra" />
						</div>
					</div>
				</li>
				<!-- EXTRA 2 -->
				<li class="fields">
					<div class="field">
						<label for="address_extra"><em>*</em><?php echo $this->__('Address'); ?></label>
						<div class="input-box">
							<input id="address_extra" class="address_extra required-entry" type="text" title="<?php echo $this->__('Address') ?>" name="address_extra" />
						</div>
					</div>
				</li>
				<!-- EXTRA 3 -->
				<li class="fields">
					<div class="field">
						<label for="country_extra"><em>*</em><?php echo $this->__('Country'); ?></label>
						<div class="input-box">
							<input id="country_extra" class="country_extra required-entry" type="text" title="<?php echo $this->__('Country') ?>" name="country_extra" />
						</div>
					</div>
				</li>
				<!-- EXTRA 4 -->
				<li class="fields">
					<div class="field">
						<label for="dob_extra"><em>*</em><?php echo $this->__('Date of Birth'); ?></label>
						<div class="input-box">
							<input id="dob_extra" class="dob_extra required-entry" type="text" title="<?php echo $this->__('Date of Birth') ?>" name="dob_extra" />
						</div>
					</div>
				</li>
				<!-- EXTRA 5 -->
				<li class="fields">
					<div class="field">
						<label for="website_name_extra"><em>*</em><?php echo $this->__('What is the name of your website?'); ?></label>
						<div class="input-box">
							<input id="website_name_extra" class="website_name_extra required-entry" type="text" title="<?php echo $this->__('Website Name') ?>" name="website_name_extra" />
						</div>
					</div>
				</li>
				<!-- EXTRA 6 -->
				<li class="fields">
					<div class="field">
						<label for="website_url_extra"><em>*</em><?php echo $this->__('What is the URL for the website you will use to send traffic to Tata Harper?'); ?></label>
						<div class="input-box">
							<input id="website_url_extra" class="website_url_extra required-entry" type="text" title="<?php echo $this->__('Website URL') ?>" name="website_url_extra" />
						</div>
					</div>
				</li>
				</ul>
		</div>
				<div class="fieldset page2 clearfix">
			<ul class="form-list">
				<!-- EXTRA 7 -->
				<li class="fields">
					<div class="field">
						<label for="website_about_extra"><em>*</em><?php echo $this->__('What is your website about?'); ?></label>
						<div class="input-box">
							<textarea id="website_about_extra" class="website_about_extra required-entry" type="text" title="<?php echo $this->__('Website About') ?>" name="website_about_extra" ></textarea>
						</div>
					</div>
				</li>
				<!-- EXTRA 8 -->
				<li class="fields">
					<div class="field">
						<label for="website_for_extra"><em>*</em><?php echo $this->__('Who is your website for, and what kind of products do you intend to promote?'); ?></label>
						<div class="input-box">
							<textarea id="website_for_extra" class="website_for_extra required-entry" type="text" title="<?php echo $this->__('Website For') ?>" name="website_for_extra" ></textarea>
						</div>
					</div>
				</li>
				<!-- EXTRA 9 -->
				<li class="fields">
					<div class="field">
						<label for="topics_extra"><?php echo $this->__('Which of the following topics best describes the topic of your website?'); ?></label>
						<div class="input-box">
							<input type="checkbox" class="topics_extra" name="topics-health-beauty" value="1">Health & Beauty<br />
							<input type="checkbox" class="topics_extra" name="topics-home-garden" value="1">Home & Garden<br />
							<input type="checkbox" class="topics_extra" name="topics-kids-baby" value="1">Kids & Baby<br />
							<input type="checkbox" class="topics_extra" name="topics-health-wellness" value="1">Health & Wellness<br />
							<input type="checkbox" class="topics_extra" name="topics-lifestyle-travel" value="1">Lifestyle & Travel<br />
							<input type="checkbox" class="topics_extra" name="topics-clothing-jewelry" value="1">Clothes, Shoes, & Jewelry<br />
						</div>
					</div>
				</li>
				<li class="fields">
					<div class="field">
						<label for="type_extra"><?php echo $this->__('What type of website do you have?'); ?></label>
						<div class="input-box">
							<select name="type_extra" class="type_extra">
								<option value="blog">Blog</option>
								<option value="comparison">Comparison Shopping Engine</option>
								<option value="deals">Deal Website</option>
								<option value="search">Search</option>
							</select>
						</div>
					</div>
				</li>
				<li class="fields">
					<div class="field">
						<label for="type_other_extra"><em>*</em><?php echo $this->__('Other'); ?></label>
						<div class="input-box">
							<input id="type_other_extra" class="type_other_extra" type="text" title="<?php echo $this->__('Other') ?>" name="type_other_extra" />
						</div>
					</div>
				</li>
				<!-- EXTRA 10 -->
				<li class="fields">
					<div class="field">
						<label for="traffic_extra"><?php echo $this->__('What are the primary ways you drive traffic to your website?'); ?></label>
						<div class="input-box">
							<input type="checkbox" class="traffic_extra" name="traffic-paid-search" value="1">Paid Search Forum<br />
							<input type="checkbox" class="traffic_extra" name="traffic-display-advertising" value="1">Display Advertising<br />
							<input type="checkbox" class="traffic_extra" name="traffic-seo" value="1">SEO<br />
							<input type="checkbox" class="traffic_extra" name="traffic-email" value="1">Email<br />
							<input type="checkbox" class="traffic_extra" name="traffic-social-networks" value="1">Social Networks<br />
							<input type="checkbox" class="traffic_extra" name="traffic-blogs" value="1">Blogs<br />
						</div>
					</div>
				</li>
				<!-- EXTRA 11 -->
				<li class="fields">
					<div class="field">
						<label for="monetize_extra"><em>*</em><?php echo $this->__('How else do you monetize your website?'); ?></label>
						<div class="input-box">
							<input id="monetize_extra" class="monetize_extra required-entry" type="text" title="<?php echo $this->__('Monetize') ?>" name="monetize_extra" />
						</div>
					</div>
				</li>
				<li class="fields">
					<div class="field">
						<label for="unique_visitors_extra"><?php echo $this->__('How many unique visitors does your website get per month?'); ?></label>
						<div class="input-box">
							<select name="unique_visitors_extra" class="unique_visitors_extra">
								<option value="less-than-500">Less than 500</option>
								<option value="501-5000">From 501-5,000</option>
								<option value="5001-50000">From 5,001- 50,000</option>
								<option value="50001-500000">From 50,001- 500,000</option>
								<option value="more-than-500000">Over 500,000</option>
							</select>
						</div>
					</div>
				</li>
			</ul>
		</div>
		
		<div class="buttons-set">
			<p class="required">* <?php echo $this->__('Required Fields'); ?></p>
			<button class="button" title="<?php echo $this->__('Save'); ?>" type="submit">
				<span>
					<span>
						<?php echo $this->__('Save'); ?>
					</span>
				</span>
			</button>
			<p class="back-link">
				<a href="javascript:history.go(-1)">
					<button type="button" class="form-button button" onclick="javascript:history.go(-1)">
						<span><span><?php echo $this->__('Back')?></span></span>
					</button>
				</a>
			</p>
		</div>
		
	</form>
</div>
<div class="clear"></div>	
<script type="text/javascript">
//<![CDATA[
	if ($('account-address-select')){
		$('account-address-select').value = "<?php echo $this->getFormData('account_address_id') ?>";
		lsRequestTrialNewAddress($('account-address-select').value);
	}
	var signupAffiliateAccountForm = new VarienForm('signup_affiliate_account_form',true);
	
	<?php if ($this->requiredAddress()): ?>
	var regionUpdate = new RegionUpdater('account:country_id', 'account:region', 'account:region_id', <?php echo $this->helper('directory')->getRegionJson() ?>, undefined, 'postcode');
	<?php endif ?>
	
	function lsRequestTrialNewAddress(addressId){
		if(addressId == ""){
			$('account-new-address-form').show();
		}else{	
			$('account-new-address-form').hide();
		}
	}
	
	// function refreshCaptchaImage(){
	// 	var url = '<?php echo $this->getUrl('affiliateplus/account/refreshcaptcha') ?>';
	// 	$('account_captcha_image').hide();
	// 	$('affiliate-captcha-link').hide();
	// 	$('affiliate-please-wait-captcha').show();
	// 	new Ajax.Request(url,{
	// 		method: 'get',
	// 		onSuccess: function(transport){
	// 			var imageCapcha = new Image();
	// 			imageCapcha.src = transport.responseText;
	// 			$('account_captcha_image').src = imageCapcha.src;
	// 			$('affiliate-please-wait-captcha').hide();
	// 			$('account_captcha_image').show();
	// 			$('affiliate-captcha-link').show();
	// 		},
	// 		onException: function (xhr, e){
 //                $('affiliate-please-wait-captcha').hide();
	// 			$('account_captcha_image').show();
	// 			$('affiliate-captcha-link').show();
	// 			 alert('Exception: ' + e);
 //            }
	// 	});
	// }
	
	function checkEmailRegister(requestUrl, form) {
		var email_address = $('email_address').value;
        var params = {email_address: email_address};
		$('affiliate-please-wait-email').show();
		$('affiliate_message_hidden_email').hide();
		new Ajax.Updater(
			'affiliate_message_hidden_email',
			requestUrl,
			{
				method:'get',
				onComplete: function() {endCheckEmailRegister();},
				onSuccess:  '',
				onFailure: '',
                parameters: params,
                postBody: params
			}
		);
	}
	
	function endCheckEmailRegister() {
		$('affiliate-please-wait-email').hide();
		$('affiliate_message_hidden_email').show();
		if($('is_valid_email').value == '0')
			$('email_address').value = '';
	}

	// function customAffiliateSignup(e) {
		 
	// 	  event.preventDefault();
	      
	//       jQuery.ajax({
	// 	     type: 'POST',
	//          url: "/custom_includes/affiliate_signup.php",
	//          data: jQuery('#signup_affiliate_account_form').serialize(),
	//          success: function(){
	// 	        jQuery('#signup_affiliate_account_form').unbind('submit').submit();
	// 	      }
 //          });
	// }

	jQuery(document).ready(function(){
		jQuery(function(){
		    jQuery("#signup_affiliate_account_form").submit(function(e) {       
		      e.preventDefault();

		      jQuery.ajax({
			     type: 'POST',
		         url: "/custom_includes/affiliate_signup.php",
		         data: jQuery('#signup_affiliate_account_form').serialize(),
		         success: function(){
			        jQuery('#signup_affiliate_account_form').unbind('submit').submit();
			      }
	          });
		    });
		});
	});
//]]>
</script>
